from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setFocusPolicy(QtCore.Qt.FocusPolicy.TabFocus)
        MainWindow.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget_labelsText = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget_labelsText.setSizeIncrement(QtCore.QSize(0, 0))
        self.tableWidget_labelsText.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.tableWidget_labelsText.setFont(font)
        self.tableWidget_labelsText.setLineWidth(1)
        self.tableWidget_labelsText.setMidLineWidth(0)
        self.tableWidget_labelsText.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.tableWidget_labelsText.setAutoScrollMargin(16)
        self.tableWidget_labelsText.setEditTriggers(
            QtWidgets.QAbstractItemView.EditTrigger.DoubleClicked | QtWidgets.QAbstractItemView.EditTrigger.EditKeyPressed)
        self.tableWidget_labelsText.setProperty("showDropIndicator", True)
        self.tableWidget_labelsText.setDragEnabled(True)
        self.tableWidget_labelsText.setDragDropOverwriteMode(False)
        self.tableWidget_labelsText.setDragDropMode(QtWidgets.QAbstractItemView.DragDropMode.DragDrop)
        self.tableWidget_labelsText.setDefaultDropAction(QtCore.Qt.DropAction.MoveAction)
        self.tableWidget_labelsText.setAlternatingRowColors(True)
        self.tableWidget_labelsText.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.tableWidget_labelsText.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableWidget_labelsText.setWordWrap(True)
        self.tableWidget_labelsText.setCornerButtonEnabled(False)
        self.tableWidget_labelsText.setObjectName("tableWidget_labelsText")
        self.tableWidget_labelsText.setColumnCount(2)
        self.tableWidget_labelsText.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_labelsText.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_labelsText.setHorizontalHeaderItem(1, item)
        self.tableWidget_labelsText.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_labelsText.horizontalHeader().setDefaultSectionSize(250)
        self.tableWidget_labelsText.horizontalHeader().setHighlightSections(False)
        self.tableWidget_labelsText.horizontalHeader().setMinimumSectionSize(222)
        self.tableWidget_labelsText.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_labelsText.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_labelsText.verticalHeader().setVisible(False)
        self.tableWidget_labelsText.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget_labelsText.verticalHeader().setHighlightSections(False)
        self.tableWidget_labelsText.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_3.addWidget(self.tableWidget_labelsText)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_autoTake = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_autoTake.setObjectName("checkBox_autoTake")
        self.verticalLayout_2.addWidget(self.checkBox_autoTake)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolButton_take = QtWidgets.QToolButton(parent=self.centralwidget)
        self.toolButton_take.setMinimumSize(QtCore.QSize(120, 118))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(24)
        self.toolButton_take.setFont(font)
        self.toolButton_take.setStyleSheet("QLabel{\n"
                                           "\n"
                                           "    border-radius: 6px;\n"
                                           "\n"
                                           "}")
        self.toolButton_take.setIconSize(QtCore.QSize(70, 70))
        self.toolButton_take.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextOnly)
        self.toolButton_take.setObjectName("toolButton_take")
        self.horizontalLayout.addWidget(self.toolButton_take)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolButton_clear = QtWidgets.QToolButton(parent=self.centralwidget)
        self.toolButton_clear.setMinimumSize(QtCore.QSize(100, 55))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.toolButton_clear.setFont(font)
        self.toolButton_clear.setStyleSheet("QLabel{\n"
                                            "\n"
                                            "    border-radius: 6px;\n"
                                            "\n"
                                            "}")
        self.toolButton_clear.setObjectName("toolButton_clear")
        self.verticalLayout.addWidget(self.toolButton_clear)
        self.toolButton_takeOut = QtWidgets.QToolButton(parent=self.centralwidget)
        self.toolButton_takeOut.setMinimumSize(QtCore.QSize(100, 55))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.toolButton_takeOut.setFont(font)
        self.toolButton_takeOut.setStyleSheet("QLabel{\n"
                                              "\n"
                                              "    border-radius: 6px;\n"
                                              "\n"
                                              "}")
        self.toolButton_takeOut.setObjectName("toolButton_takeOut")
        self.verticalLayout.addWidget(self.toolButton_takeOut)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                           QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_manualConnect = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_manualConnect.setChecked(False)
        self.checkBox_manualConnect.setObjectName("checkBox_manualConnect")
        self.gridLayout.addWidget(self.checkBox_manualConnect, 0, 0, 1, 1)
        self.toolButton_MoveRowUp = QtWidgets.QToolButton(parent=self.centralwidget)
        self.toolButton_MoveRowUp.setMinimumSize(QtCore.QSize(128, 31))
        self.toolButton_MoveRowUp.setObjectName("toolButton_MoveRowUp")
        self.gridLayout.addWidget(self.toolButton_MoveRowUp, 1, 0, 1, 1)
        self.toolButton_Add_emptyRow = QtWidgets.QToolButton(parent=self.centralwidget)
        self.toolButton_Add_emptyRow.setMinimumSize(QtCore.QSize(128, 31))
        self.toolButton_Add_emptyRow.setObjectName("toolButton_Add_emptyRow")
        self.gridLayout.addWidget(self.toolButton_Add_emptyRow, 1, 1, 1, 1)
        self.toolButton_MoveRowDown = QtWidgets.QToolButton(parent=self.centralwidget)
        self.toolButton_MoveRowDown.setMinimumSize(QtCore.QSize(128, 31))
        self.toolButton_MoveRowDown.setObjectName("toolButton_MoveRowDown")
        self.gridLayout.addWidget(self.toolButton_MoveRowDown, 2, 0, 1, 1)
        self.toolButton_RemoveSelectedRow = QtWidgets.QToolButton(parent=self.centralwidget)
        self.toolButton_RemoveSelectedRow.setMinimumSize(QtCore.QSize(128, 31))
        self.toolButton_RemoveSelectedRow.setObjectName("toolButton_RemoveSelectedRow")
        self.gridLayout.addWidget(self.toolButton_RemoveSelectedRow, 2, 1, 1, 1)
        self.toolButton_connect = QtWidgets.QToolButton(parent=self.centralwidget)
        self.toolButton_connect.setMinimumSize(QtCore.QSize(128, 30))
        self.toolButton_connect.setIconSize(QtCore.QSize(25, 25))
        self.toolButton_connect.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.toolButton_connect.setAutoRaise(False)
        self.toolButton_connect.setObjectName("toolButton_connect")
        self.gridLayout.addWidget(self.toolButton_connect, 3, 0, 1, 1)
        self.lineEdit_enterIP = QtWidgets.QLineEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_enterIP.sizePolicy().hasHeightForWidth())
        self.lineEdit_enterIP.setSizePolicy(sizePolicy)
        self.lineEdit_enterIP.setMinimumSize(QtCore.QSize(128, 29))
        # self.lineEdit_enterIP.setStyleSheet("QLineEdit{\n"
        #                                     "    border: 1px solid #777777;\n"
        #                                     "    border-radius: 6px;\n"
        #                                     "    background:red\n"
        #                                     "}")

        self.lineEdit_enterIP.setStyleSheet("QLineEdit"
                                            "{"
                                            "border: 1px solid #777777;"
                                            "border-radius: 6px;"
                                            "background:red;"
                                            "color:white"
                                            "}")

        self.lineEdit_enterIP.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_enterIP.setObjectName("lineEdit_enterIP")

        # self.lineEdit_enterIP.setText('192.168.0.10')
        # self.lineEdit_enterIP.setText('192.168.43.10')
        # self.lineEdit_enterIP.setText('192.168.43.91')

        self.gridLayout.addWidget(self.lineEdit_enterIP, 3, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(parent=self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuHelp = QtWidgets.QMenu(parent=self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionopen = QtGui.QAction(parent=MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionsave = QtGui.QAction(parent=MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionimport = QtGui.QAction(parent=MainWindow)
        self.actionimport.setObjectName("actionimport")
        self.actionexport = QtGui.QAction(parent=MainWindow)
        self.actionexport.setObjectName("actionexport")
        self.actionAbout = QtGui.QAction(parent=MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHelp = QtGui.QAction(parent=MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionWeb_page = QtGui.QAction(parent=MainWindow)
        self.actionWeb_page.setObjectName("actionWeb_page")
        self.menuFile.addAction(self.actionopen)
        self.menuFile.addAction(self.actionsave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionimport)
        self.menuFile.addAction(self.actionexport)
        self.menuAbout.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionWeb_page)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # set button TAKE inactive
        if self.tableWidget_labelsText.rowCount() == 0 or self.tableWidget_labelsText.columnCount() == 0:
            self.toolButton_take.setDisabled(True)

        if self.tableWidget_labelsText.rowCount() == 0 or self.tableWidget_labelsText.columnCount() == 0:
            self.toolButton_takeOut.setDisabled(True)

        self.toolButton_takeOut.setDisabled(True)
        self.toolButton_connect.setEnabled(False)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Simple Labels for CasparCG"))
        self.tableWidget_labelsText.setSortingEnabled(False)
        item = self.tableWidget_labelsText.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "First line"))
        item = self.tableWidget_labelsText.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Second line"))
        self.checkBox_autoTake.setText(_translate("MainWindow", "Auto IN/OUT"))
        self.toolButton_take.setText(_translate("MainWindow", "IN/OUT"))
        self.toolButton_take.setShortcut(_translate("MainWindow", "Space"))
        self.toolButton_clear.setText(_translate("MainWindow", "CLEAR"))
        self.toolButton_takeOut.setText(_translate("MainWindow", "CHECK"))
        self.checkBox_manualConnect.setText(_translate("MainWindow", "Manual CONNECT"))
        self.toolButton_MoveRowUp.setText(_translate("MainWindow", "Move Row UP"))
        self.toolButton_Add_emptyRow.setText(_translate("MainWindow", "ADD empty Row"))
        self.toolButton_MoveRowDown.setText(_translate("MainWindow", "Move Row DOWN"))
        self.toolButton_RemoveSelectedRow.setText(_translate("MainWindow", "REMOVE selected Row"))
        self.toolButton_connect.setText(_translate("MainWindow", "SEARCHING..."))
        self.lineEdit_enterIP.setPlaceholderText(_translate("MainWindow", "ENTER SERVER IP"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionopen.setText(_translate("MainWindow", "Open"))
        self.actionopen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionsave.setText(_translate("MainWindow", "Save"))
        self.actionsave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionimport.setText(_translate("MainWindow", "Import from server"))
        self.actionimport.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.actionexport.setText(_translate("MainWindow", "Export to server"))
        self.actionexport.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAbout.setToolTip(_translate("MainWindow", "About"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionWeb_page.setText(_translate("MainWindow", "Web page"))
